### ISSUE TITLE
Can't find fonts unless in ./Fonts/

### ISSUE THREAD

**Issue by defjaf** [ImperialCollegeLondon/imperial_latex_templates#1]
I am on macOS 14.3.1 using MacTeX.

I am trying to get the new letterhead to work without copying all the files into the directory of my *.tex files each time.

I have successfully installed the *.cls files into the `$TEXINPUTS` directory, and the letterhead image files into `$TEXINPUTS/Images/`. 

However, I can only seem to use the fonts when they are copied into `./Fonts` alongside the latex file. I have tried installing the *.ttf files into my user or system fonts directories (with FontBook on macOS). Usually, this is all that is necessary for xelatex, but right now this doesn't seem to work with your *.cls files. I get the following error:
```
! Package fontspec Error: The font "ImperialSansText-Regular.ttf" cannot be
(fontspec)                found.

```

Once installed as a normal macOS font, the Imperial fonts *are* found by xelatex in other circumstances. For example, the following file compiles just fine, and looks correct:
```tex
%!TEX program = xelatex
\documentclass{article} 
\usepackage{fontspec} 
\setromanfont{ImperialSansText-Extralight} 
\begin{document} 
ImperialSans Light \texttt{somethingelse} 
\end{document}
```

This isn't a show-stopper — I can just copy the files as needed — but it's annoying.

**Comment by defjaf** [comment]
Seems to work! Thanks for the quick fix. (I think the instructions should perhaps be more explicit about how and where to install the different bits and pieces. The pointer at https://brand.imperial.ac.uk/document/68#/-/about-templates to https://en.wikibooks.org/wiki/LaTeX/Installing_Extra_Packages is not really clear about the fonts and images.)

**Comment by dham** [comment]
I think that's a fair criticism, but it's really a criticism of that source. The correct way to do fonts, in particular, is OS dependent and may even depend on which LaTeX distribution the user employs. If someone has time to work through all the combinations (and I currently don't), they should probably do os in the wikibook for the benefit of the LaTeX community at large.
